# Site metadata for easy reference
site_info:
  name: "Dheirya Bhatt's Website"
  description: "Developer & Designer - Building beautiful digital experiences"
  author: "Dheirya Bhatt"
  version: "1.0.0"
  
# Navigation structure
navigation:
  - name: "Home"
    url: "/"
    icon: "home"
  - name: "Blog" 
    url: "/blog/"
    icon: "blog"

# Animation settings
flipdot:
  text: "Dee's Blog!"
  delay: 10
  loop: true
  loop_delay: 4000
  
# Social links
social:
  github: "DheiryaBhatt"
  email: "bhattdheirya@gmail.com"
  university: "https://www.uni-paderborn.de/"
  employer: "https://www.dspace.com/"